baseurl = "http://patricialhorvath.com/"
languageCode = "en-us"
title = "Patricia Horvath"
theme = "patti"
[[ menu.main ]]
  name = "Book"
  weight = -110
  identifier = "all-the-difference"
  url = "/all-the-difference/"
[[ menu.main ]]
  name = "About"
  weight = -100
  identifier = "about"
  url = "/about/"
[[ menu.main ]]
  name = "Reviews & Interviews"
  weight = -90
  identifier = "reviews-and-interviews"
  url = "/reviews-and-interviews/"
[[ menu.main ]]
  name = "Other Writing"
  weight = -80
  identifier = "publications"
  url = "/publications/"
[[ menu.main ]]
  name = "Events"
  weight = -70
  identifier = "events"
  url = "/events/"
[[ menu.main ]]
  name = "Contact"
  weight = -60
  identifier = "contact"
  url = "/contact/"
